scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['enerchest-server:5000']
        labels:
          service: 'app-exporter'
          group: 'testing'
          name: 'app-exporter'

